### PR TITLE
multi: Convert rpcserver lifecycle to context.

### LINKED ISSUE #2037: Shutdown race
```2020-01-22 16:05:08.285 [INF] DCRD: Received signal (interrupt).  Shutting down...
2020-01-22 16:05:08.285 [WRN] SRVR: Server shutting down
2020-01-22 16:05:08.285 [WRN] RPCS: RPC server shutting down
2020-01-22 16:05:08.291 [INF] RPCS: RPC server shutdown complete
2020-01-22 16:05:08.292 [INF] BMGR: Block manager shutting down
2020-01-22 16:05:08.294 [INF] SRVR: seeder 'testnet-seed-1.decred.org' error: Get https://testnet-seed-1.decred.org/api/addrs?ipversion=0&pver=0&services=1: context canceled
==================
WARNING: DATA RACE
Write at 0x00c00ec2a6a8 by goroutine 33:
  sync.(*WaitGroup).Wait()
      /home/user/apps/go/src/internal/race/race.go:41 +0xee
  main.(*rpcServer).Stop()
      /home/user/projetos/decred/dcrd/rpcwebsocket.go:1294 +0x1b7
  main.(*server).Run()
      /home/user/projetos/decred/dcrd/server.go:2553 +0x3cd
  main.dcrdMain.func5()
      /home/user/projetos/decred/dcrd/dcrd.go:194 +0x4c

Previous read at 0x00c00ec2a6a8 by goroutine 36:
  sync.(*WaitGroup).Add()
      /home/user/apps/go/src/internal/race/race.go:37 +0x18d
  main.(*wsNotificationManager).Start()
      /home/user/projetos/decred/dcrd/rpcwebsocket.go:1286 +0x4b
  main.(*rpcServer).Start()
      /home/user/projetos/decred/dcrd/rpcserver.go:5499 +0x42a
  main.(*server).Run.func1()
      /home/user/projetos/decred/dcrd/server.go:2514 +0x59
```

I believe this is due to the `wsNotificationManager.Start()` being called from a different goroutine than `wsNotificationManager.Stop()` (starting [here](https://github.com/decred/dcrd/blob/e3547d0822db291479ea67a914feaa70806f0828/server.go#L2513-L2514)).

A way to solve this would be to have all subsystems start their own handling goroutines (instead of having `server.Run()` do it) while the server itself calls each `Start()` serially. 

This is a low priority race since it involves node shutdown and can't really cause data loss. I'm creating the issue just to have it documented.

### PR DESCRIPTION
**Pull request by dnldd**
This updates the `rpcserver` and `wsNotificationManager` lifecycle processes to use a context.

Resolves  #2037

### CODE REVIEW

File: rpcserver.go [hunk 1]
```diff
@@ -5583,7 +5580,7 @@ type rpcserverConfig struct {
 }
 
 // newRPCServer returns a new instance of the rpcServer struct.
-func newRPCServer(config *rpcserverConfig) (*rpcServer, error) {
+func newRPCServer(ctx context.Context, config *rpcserverConfig) (*rpcServer, error) {
```
Comment (matheusd) [inline rpcserver.go]: Accepting the ctx in both `newRPCServer` and `Run` makes it so that callers need to remember to pass _the same_ context to both.

It's probably better to follow the convention set in other components to only pass the context in `Run()`.

I understand you did that due to the several selects such as in `NotifyBlockConnected` but maybe it would be better to just _not_ perform those sends if the underlying `m.ctx` isn't set (which would be done in `Run()`). The interpretation of that is "if the notification manager isn't running, there's no one to notify".

Basically what I'm thinking of is:

```go
type wsNotificationManager struct {
  //...
  mtx sync.RWMutex
  ctx context.Context
}

func newWsNotificationManager(server *rpcServer) *wsNotificationManager {
//...
}

func (m *wsNotificationManager) run(ctx context.Context) {
  m.mtx.Lock()
  m.ctx = ctx
  m.mtx.Unlock()
  //...
  m.mtx.Lock()
  m.ctx = nil
  m.mtx.Unlock()
}

func (m *wsNotificationManager) NotifyBlockConnected(block *dcrutil.Block) {
  m.mtx.RLock()
  defer m.mtx.RUnlock()
  if m.ctx == nil {
    // Notification manager not started yet. Cannot send notifications.
    return
  }
  //...
}
```

I'm not sure this is worth the effort just to get the API slightly better though...

Comment (dnldd) [reply rpcserver.go]: I agree with you, that's better design overall. Will update soon. Thank you.

Comment (dnldd) [reply rpcserver.go]: implemented with some modifications, please take another look.

File: rpcwebsocket.go [hunk 2]
```diff
@@ -1276,30 +1340,23 @@ func (m *wsNotificationManager) AddClient(wsc *wsClient) {
 func (m *wsNotificationManager) RemoveClient(wsc *wsClient) {
 	select {
 	case m.queueNotification <- (*notificationUnregisterClient)(wsc):
-	case <-m.quit:
+	case <-m.ctx.Done():
 	}
 }
 
-// Start starts the goroutines required for the manager to queue and process
+// run starts the goroutines required for the manager to queue and process
```
Comment (matheusd) [inline rpcwebsocket.go]: Should improve to comment to reflect the fact that it blocks until the context is canceled (same as other servers)

File: rpcserver.go [hunk 3]
```diff
@@ -5483,20 +5471,29 @@ func (s *rpcServer) Start() {
 		})
 		s.WebsocketHandler(ws, r.RemoteAddr, authenticated, isAdmin)
 	})
+	return httpServer
+}
 
+// Run  is used by server.go to start the rpc listener.
```
Comment (matheusd) [inline rpcserver.go]: Update the comment to reflect the fact that run blocks until the context is canceled.

File: rpcwebsocket.go [hunk 4]
```diff
@@ -1276,30 +1340,23 @@ func (m *wsNotificationManager) AddClient(wsc *wsClient) {
 func (m *wsNotificationManager) RemoveClient(wsc *wsClient) {
 	select {
 	case m.queueNotification <- (*notificationUnregisterClient)(wsc):
-	case <-m.quit:
+	case <-m.ctx.Done():
```
Comment (matheusd) [inline rpcwebsocket.go]: Missing a check for nil `m.ctx`

File: rpcserver.go [hunk 5]
```diff
@@ -5179,9 +5170,11 @@ func (s *rpcServer) processRequest(ctx context.Context, request *dcrjson.Request
 }
 
 // jsonRPCRead handles reading and responding to RPC messages.
-func (s *rpcServer) jsonRPCRead(w http.ResponseWriter, r *http.Request, isAdmin bool) {
-	if atomic.LoadInt32(&s.shutdown) != 0 {
+func (s *rpcServer) jsonRPCRead(sCtx context.Context, w http.ResponseWriter, r *http.Request, isAdmin bool) {
```
[the remark this answers is not in the document]
Comment (dnldd) [reply rpcserver.go]: calling it `sCtx` there to distinguish between it and the context defined here https://github.com/decred/dcrd/blob/31a373571bc6304ea23da1838ccf809e1b98aeff/rpcserver.go#L5222

[the remark this answers is not in the document]
Comment (davecgh) [reply rpcserver.go]: Understood, but typically you use a unique name for the context inside the function when you create a child context.

[the remark this answers is not in the document]
Comment (davecgh) [reply rpcserver.go]: Understood, but typically you use a unique name for the context inside the function when you create a child context.  Like I said, it's a minor nitpick though and not worth holding this PR up over.  Something to keep in mind for the future.
