### PR TITLE
multi: Allow discrete mining with invalidated tip.

### LINKED ISSUE #2837: Cannot generate simnet blocks after invalidating tip
Reproducer:

- Run `contrib/dcr_tmux_simnet_setup.sh`
- Mine a block on dcrd1: `./mine`
- Invalidate latest block: `./ctl getbestblockhash |  ./ctl invalidateblock -`
- Attempt to mine new block: `./mine`

Generating hangs forever.

This is due to [this check](https://github.com/decred/dcrd/blob/master/internal/mining/cpuminer/cpuminer.go#L714-L719) in the CPU miner: going back to the block prior to tip makes this check fail, due to attempting to mine based on the same previous header.

One option to fix this would be to somehow reset `discretePrev` after some time has passed, when the `invalidateblock` rpc call is called or when the `regentemplate` is called.

### PR DESCRIPTION
**Pull request by davecgh**
This adds additional logic to the CPU miner's discrete mining process to detect when the block that it most recently submitted is no longer valid to prevent a hang in that case while still providing the desired behavior that waits for updated templates when invoked in rapid succession.

Fixes #2837.

### CODE REVIEW

File: blockchain/chainquery.go [hunk 1]
```diff
@@ -248,3 +248,22 @@ func (b *BlockChain) VerifyProgress() float64 {
...
 }
+
+// IsKnownInvalidBlock returns whether either the provided block is itself known
+// to be invalid or to have an invalid ancestor.  A return value of false in no
+// way implies the block is valid or only has valid ancestors.  Thus, this will
+// return false for invalid blocks that have not been proven invalid yet as well
+// as return false for blocks with invalid ancestors that have not been proven
+// invalid yet.
+//
+// It will also return false when the block provided block is unknown.
```
Comment (matheusd) [inline blockchain/chainquery.go:259]: "block provided block"

**Review by matheusd — APPROVED** [review]
Working as intended. Just noted a small typo.

File: blockchain/chainquery.go (hunk 1 above)
Comment (davecgh) [reply blockchain/chainquery.go]: Updated.

**Review by rstaudt2 — APPROVED** [review]
