### PR TITLE
mempool: Add ErrorCode to returned TxRuleErrors

### LINKED ISSUE #1900: Finer grained mempool error codes
Switch the error types returned by the mempool package to finer grained ones, so that ultimately the rpc server can return different error codes depending on whether a transaction being published is an exact duplicate of one or has other problems which are currently muxed into the same rejection code `RejectDuplicate`.

Context for the discussion:

https://matrix.to/#/!HEeJkbPRpAqgAwhXWO:decred.org/$156866527732484zYwTq:decred.org?via=decred.org

Outline of the solution:

```diff
diff --git a/mempool/error.go b/mempool/error.go
index ad878a2a..32cc734f 100644
--- a/mempool/error.go
+++ b/mempool/error.go
@@ -28,6 +28,14 @@ func (e RuleError) Error() string {
 	return e.Err.Error()
 }
 
+type ErrorCode int
+
+const (
+	ErrUnkown ErrorCode = iota
+	ErrDuplicate
+	ErrMissingInputs
+)
+
 // TxRuleError identifies a rule violation.  It is used to indicate that
 // processing of a transaction failed due to one of the many validation
 // rules.  The caller can use type assertions to determine if a failure was
@@ -35,7 +43,8 @@ func (e RuleError) Error() string {
 // ascertain the specific reason for the rule violation.
 type TxRuleError struct {
 	RejectCode  wire.RejectCode // The code to send with reject messages
-	Description string          // Human readable description of the issue
+	Code        ErrorCode
+	Description string // Human readable description of the issue
 }
 
 // Error satisfies the error interface and prints human-readable errors.
@@ -45,9 +54,9 @@ func (e TxRuleError) Error() string {
 
 // txRuleError creates an underlying TxRuleError with the given a set of
 // arguments and returns a RuleError that encapsulates it.
-func txRuleError(c wire.RejectCode, desc string) RuleError {
+func txRuleError(c wire.RejectCode, code ErrorCode, desc string) RuleError {
 	return RuleError{
-		Err: TxRuleError{RejectCode: c, Description: desc},
+		Err: TxRuleError{RejectCode: c, ErrorCode: code, Description: desc},
 	}
 }
```

Then add deprecation notice to RejectCode, switch call sites as appropriate, etc
And modify the rpc server to return a different error code as well
Need to hit that isDoubleSpendOrDuplicateError as well.

### PR DESCRIPTION
**Pull request by matheusd**
This adds the ErrorCode member to TxRuleError, filling it with
appropriate values throughout the mempool package. This allows clients
of the package to correctly identify error causes with a greater
granularity and respond appropriately.

It also deprecates the RejectCode attribute and ErrToRejectError
functions, to be removed in the next major version update of the
package.

All call sites that inspect mempool errors were updated to use the new
error codes instead of using RejectionCodes. Additional mempool tests
were added to ensure the correct behavior on some relevant cases.

Finally, given the introduction and use of a new public field, the main
module was updated to use an as-of-yet unfinished mempool v3.1.0, which
will include the required functionality.

Close #1900

### CODE REVIEW

File: blockmanager.go [hunk 1]
```diff
@@ -595,6 +595,96 @@ func (b *blockManager) handleDonePeerMsg(peers *list.List, sp *serverPeer) {
 	}
 }
 
+// errToWireRejectCode determines the wire rejection code and description for a
+// given error. This function can convert some select blockchain and mempool
+// error types to the historical rejection codes used on the p2p wire protocol.
+func errToWireRejectCode(err error) (wire.RejectCode, string) {
+	if err == nil {
+		panic("errToWireRejectCode(): err should not be nil")
```
Comment (davecgh) [inline blockmanager.go]: This is a remote exploit waiting to happen.

I describe in a bit more detail below, but in general, panics in error paths, especially those that are dealing with external data are incredibly dangerous.  This case isn't quite as bad as the one I discuss below, but this also needs to be changed to return a generic error instead.

File: blockmanager.go [hunk 2]
```diff
@@ -595,6 +595,96 @@ func (b *blockManager) handleDonePeerMsg(peers *list.List, sp *serverPeer) {
...
+		// Rejected due to duplicate.
+		case blockchain.ErrDuplicateBlock:
+			code = wire.RejectDuplicate
+
+		// Rejected due to obsolete version.
+		case blockchain.ErrBlockVersionTooOld:
+			code = wire.RejectObsolete
+
+		// Rejected due to checkpoint.
+		case blockchain.ErrCheckpointTimeTooOld:
```
Comment (davecgh) [inline blockmanager.go]: It doesn't matter much, but this could all be much more compact (and readable imo) using commas for the additional cases instead of `fallthrough`.

e.g.
```Go
	switch err.ErrorCode {
	case blockchain.ErrCheckpointTimeTooOld, blockchain.ErrDifficultyTooLow,
		blockchain.ErrBadCheckpoint, blockchain.ErrForkTooOld:

		code = wire.RejectCheckpoint
	}

	reason = err.Error()
```

The same holds true for the others.

File: mempool/mempool_test.go [hunk 3]
```diff
@@ -971,6 +971,10 @@ func TestVoteOrphan(t *testing.T) {
 		t.Fatalf("ProcessTransaction: accepted transaction references " +
 			"outputs of unknown or fully-spent transaction")
 	}
+	if code, ok := extractErrorCode(err); !ok || code != ErrOrphan {
```
Comment (davecgh) [inline mempool/mempool_test.go]: I believe this, and all the other cases below, can just replace the `if err == nil` case since if the error is nil it certainly won't be the expected code.

Then, if combined with the suggest `IsErrorCode` function, these can all turn into the, what is in my opinion more readable:

```Go
if !IsErrorCode(err, ErrOrphan) {
	t.Fatalf(....)
}
```

File: mempool/mempool.go [hunk 4]
```diff
@@ -970,16 +970,10 @@ func (mp *TxPool) maybeAcceptTransaction(tx *dcrutil.Tx, isNew, rateLimit, allow
...
 			mp.cfg.Policy.MaxTxVersion)
 		if err != nil {
-			// Attempt to extract a reject code from the error so
-			// it can be retained.  When not possible, fall back to
-			// a non standard error.
-			rejectCode, found := extractRejectCode(err)
-			if !found {
-				rejectCode = wire.RejectNonstandard
-			}
+			txre := err.(RuleError).Err.(TxRuleError)
```
[the remark this answers is not in the document]
Comment (matheusd) [reply mempool/mempool.go]: I introduced the `wrapTxRuleError` instead of going back to the previous code due to having to now override both `RejectCode` and `ErrorCode`.
