### PR TITLE
blockchain: Reverse utxo set semantics.

### LINKED ISSUE #618: mempool utxo set is incorrect
The mempool utxo set handling is wrong as it does not consider any unspent outputs in the latest block to be part of the utxo set.  This causes issues with clients such as wallets that spend very new outputs that just got mined in the last block.

What's even more baffling here is not the missing outputs of the latest block, but that mempool outputs themselves are still allowed to be spent.

The reason for this bug is that there is confusion over what dcrd's block validation is for.  Rather than thinking about blocks as invalid until they are confirmed, all blocks should be considered valid unless the next block in the main chain has invalidated them (I fixed this in wallet a while ago, and this is why with minconf=0 or 1 it still does choose to spend these outputs).

Thankfully this is NOT an issue for block processing, so fixing this does not involve a hard fork.

### PR DESCRIPTION
**Pull request by davecgh**
## NOTE: This PR currently requires a full chain download. If you plan to test it, please make a copy of your existing data directory first.

---

### Testing Notes

This PR does not yet have database migration code and is completely incompatible with the current v4 database format.  Thus a full chain download is required.  dcrd will exit with error in the case you attempt to run it against an existing v4 database and the new database it creates will be v5, so if you try to run an older software version against the new database, you will get an error message similar to `Unable to start server on [:9108]: the current blockchain database is no longer compatible with this version of the software (5 > 4).`

The migration code will be added via a separate PR.

This is the biggest change to dcrd to date and, as such, will need a significant amount of testing and careful review.

---

This modifies the way the unspent transaction output set is handled to reverse its current semantics so that it is optimized for the typical case, provides simpler handling, and resolves various issues with the previous approach.  In addition, it updates the `transaction`, `address`, and `existsaddress` indexes to no longer remove entries from blocks that have been disapproved as, in all cases, the data still exists in the blockchain and thus should be queryable via the indexes even though there is special handling applied which treats them as if they did not exist in certain regards.

Prior to this change, transactions in the regular tree were not applied to the utxo set until the next block was processed and did not vote against them.  However, that approach has several undesirable consequences such as temporarily "invisible" utxos that are actually spendable, disapproved transactions missing from indexes even though they are still in the blockchain, and poor performance characteristics.

In a certain sense, the previous approach could be viewed as the transactions not being valid until they were approved, however, that is not really true because it was (and still is) perfectly acceptable to spend utxos created by transactions in the regular tree of the same block so long as they come before the transactions that spend them. Further, utxos from a transaction in the regular tree of a block can be spent in the next block so long as that block does not disapprove them, which further illustrates that the utxos are actually valid unless they are disapproved.

Consequently, this modifies that behavior to instead make the utxo set always track the most recent block and remove the regular transactions in the parent when a block votes against them.  This approach is significantly more efficient for the normal case where the previous block is not disapproved by its successor.

Also, the terminology is changed in several places to refer to disapproved blocks and transaction trees as opposed to invalid, because invalid implies the tree/block is malformed or does not follow the consensus rules.  On the contrary, when a block votes against its parent, it is only voting against regular transaction tree of the parent.  Both the block and transaction tree are still valid in that case, only the regular transaction tree is treated as if it never existed in terms of effects on the utxo set and duplicate transaction semantics.

High level overview of changes:
- Modify the utxo viewpoint to reverse semantics as previously described
  - Remove all code related to stake viewpoints
  - Change all block connection code in the viewpoint to first undo all
    transactions in the regular tree of the parent block if the current
    one disapproves it then connect all of the stake txns followed by
    the regular transactions in the block
    - NOTE: The order here is important since stake transactions are not
      allowed to spend outputs from the regular transactions in the same
      block as the next block might disapprove them
  - Change all block disconnection code in the viewpoint to first undo
    all the transactions in the regular and stake trees of the block
    being disconnected, and then resurrect the regular transactions in
    the parent block if the block being disconnected disapproved of it
  - Introduce a new type named `viewFilteredSet` for handling sets
    filtered by transactions that already exist in a view
  - Introduce a function on the viewpoint for specifically fetching the
    inputs to the regular transactions
  - Update `mempool` block connection and disconnection code to match the
    new semantics
  - Update all tests to handle the new semantics
- Modify the best state number of transactions to include all
  transactions in all blocks regardless of disapproval because they
  still had to be processed and still exist in the blockchain
- Remove include recent block parameter from `mempool.FetchTransaction`
  since the utxoset now always includes the latest block
  - This also has the side effect of correcting some unexpected results
    such as coinbases in the most recent block being incorrectly
    reported as having zero confirmations
- Modify `mempool` utxo fetch logic to use a cached disapproved view, when
  needed, rather than recreating the view for every new transaction
  added to it
- Update spend journal to include all transactions in the block instead
  of only stake transactions from the current block and regular
  transactions from the parent block
- Modify tx and address indexes to store the block index of each tx
  along with its location within the files and update the query
  functions to return the information as well
- Change the `tx`, `address`, and `existsaddress` indexes to index all
  transactions regardless of their disapproval
  - This also corrects several issues such as the inability to query and
    retrieve transactions that exist in a disapproved block
- Update all RPC commands that return verbose transaction information
  to set that newly available block index information properly
- Rename `IsRegTxTreeKnownDisapproved` in the `mining.TxSource` interface to
  `IsRegTxTreeKnownDisapproved`
  - NOTE: This will require a major bump to the mining module before
    the next release
- Rename several `utxoView` instances to `view` for consistency
- Rename several variables that dealt with disapproved trees from
  names that contained `Invalid` to ones that contain `Disapproved`

---

This is work towards #1145.
Fixes #618.

### CODE REVIEW

**Comment by chappjc** [comment]
Just completed a full block download successfully, in almost exactly 30 minutes with a single LAN peer.  I will be testing a fresh sync of dcrdata with this.

**Comment by davecgh** [comment]
Some additional details on one of the issues this also fixes:

Before:
```
$ dcrctl getbestblockhash | dcrctl getblock - | jq -r .tx[0] | dcrctl getrawtransaction - 1
{
  "txid": "0a1a046784c0cbe2e639dc8b79debe2def79b99e2f4ac8a6b055271a77843925",
...
 "vin": [
...
 ],
"vout": [
...
 ],
...
 "blockheight": 0               <----- This is a bug fixed by this PR
...
}
```

After:
```
$ dcrctl getbestblockhash | dcrctl getblock - | jq -r .tx[0] | dcrctl getrawtransaction - 1
{
  "txid": "0a1a046784c0cbe2e639dc8b79debe2def79b99e2f4ac8a6b055271a77843925",
...
  "vin": [
...
  ],
  "vout": [
...
  ],
...
  "blockheight": 278164,
...
}
```

**Comment by davecgh** [comment]
Some additional details on another one of the issues this also fixes:

Before:
```
$ dcrctl getbestblockhash | dcrctl getblock - | jq -r .tx[0] | dcrctl gettxout - 0
{
  "bestblock": "0000000000000000396d8aba7c7c706562c4b962608812d69347af8cd2e05a94",
  "confirmations": 0,                       <----- This is a bug fixed by this PR
...
  "coinbase": true
}
```

After:
```
$ dcrctl getbestblockhash | dcrctl getblock - | jq -r .tx[0] | dcrctl gettxout - 0
{
  "bestblock": "0000000000000000396d8aba7c7c706562c4b962608812d69347af8cd2e05a94",
  "confirmations": 1,
...
  "coinbase": true
}
```

**Comment by davecgh** [comment]
Some additional details on a third issue this also fixes:

Before:
```
$ dcrctl getbestblockhash | dcrctl getblock - | jq -r .tx[1] | dcrctl getrawtransaction - 1 | jq .vin
[
 {
   "txid": "211eec2881df9364ddbaf9cf0fd73cb4a43718ac46fe8fd20c0b3e4ba5d16856",
   ...
   "amountin": -1e-08,                         <--- Not filled in despite being mined
   "blockheight": 0,                           <--- Not filled in despite being mined
   "blockindex": 4294967295,                   <--- Not filled in despite being mined
   ...
 },
 ...
]
```

After:
```
$ dcrctl getbestblockhash | dcrctl getblock - | jq -r .tx[1] | dcrctl getrawtransaction - 1 | jq .vin
[
 {
   "txid": "211eec2881df9364ddbaf9cf0fd73cb4a43718ac46fe8fd20c0b3e4ba5d16856",
   ...
   "amountin": 94.24934123,
   "blockheight": 278198,
   "blockindex": 2,
   ...
 },
 ...
]
```

File: blockchain/indexers/txindex.go [hunk 1]
```diff
@@ -81,17 +86,28 @@ var (
 //
 // The serialized format for the keys and values in the tx index bucket is:
 //
-//   <txhash> = <block id><start offset><tx length>
+//   <txhash> = <block id><start offset><tx length><block index>
```
Comment (matheusd) [inline blockchain/indexers/txindex.go]: What will be the migration plans for the indexes? Always drop and recreate if enabled? Or alert and let the user do it?

File: blockchain/utxoviewpoint.go [hunk 2]
```diff
@@ -610,214 +503,185 @@ func (b *BlockChain) disconnectTransactions(view *UtxoViewpoint, block *dcrutil.
...
+	}
 
-		// Loop backwards through all of the transaction inputs (except
-		// for the coinbase which has no inputs) and unspend the
-		// referenced txos.  This is necessary to match the order of the
-		// spent txout entries.
-		if isCoinbase {
-			continue
+	// Load all of the utxos referenced by the inputs for all transactions in
+	// the block don't already exist in the utxo view from the database.
```
Comment (matheusd) [inline blockchain/utxoviewpoint.go]: "the block [that] don't already...

File: blockchain/utxoviewpoint.go [hunk 3]
```diff
@@ -610,214 +503,185 @@ func (b *BlockChain) disconnectTransactions(view *UtxoViewpoint, block *dcrutil.
...
+	// Update the best hash for view to include this block since all of its
+	// transactions have been connected.
+	view.SetBestHash(block.Hash())
+	return nil
+}
 
-			// Mark the entry as modified since it is either new
-			// or will be changed below.
-			entry.modified = true
+// disconnectBlock updates the view by disconnecting all of transactions in both
```
Comment (matheusd) [inline blockchain/utxoviewpoint.go]: "... by disconnecting all ~of~ transactions in both"

File: blockchain/utxoviewpoint.go [hunk 4]
```diff
@@ -610,214 +503,185 @@ func (b *BlockChain) disconnectTransactions(view *UtxoViewpoint, block *dcrutil.
...
+// regular tree of the previous block, and setting the best hash for the view to
+// the parent block.
+//
+// Connecting a transaction entails marking all utxos it spends as spent, and
+// adding all of the new utxos created by it.
+//
+// Disconnecting a transaction entails removing the utxos created by it and
+// restoring the outputs spent by it with the help of the provided spent txo
+// information.
+func (view *UtxoViewpoint) disconnectBlock(db database.DB, block, parent *dcrutil.Block, stxos []spentTxOut) error {
```
Comment (matheusd) [inline blockchain/utxoviewpoint.go]: Given that the usage of `stxos` is asymmetric between `connectBlock()` (where it's optional) and `disconnectBlock()` (where it's required) maybe we want to explicitly call that out (either here or in connectBlock).

Or change connectBlock to verify whether stxos is provided, given that is in fact needed for correct usage of the utxoviewpoint in the face of possibility of reorgs.

**Comment by davecgh** [comment]
Some additional details on a fourth issue this also fixes:

Before:
```
$ dcrctl getbestblockhash | dcrctl getblock - | jq -r .tx[1] | dcrctl getrawtransaction - 1 | jq -r '.blockhash'
null    <---- The block hash is not filled in despite being mined
```

After:
```
$ dcrctl getbestblockhash | dcrctl getblock - | jq -r .tx[1] | dcrctl getrawtransaction - 1 | jq -r '.blockhash'
0000000000000000b76446ea746e2a48de8f1d43cb4674725e37d044865ff800
```

File: blockmanager.go [hunk 5]
```diff
@@ -1770,56 +1799,81 @@ func (b *blockManager) handleNotifyMsg(notification *blockchain.Notification) {
...
+		// The dependencies are not removed for double spends because the only
+		// way a transaction which was not a double spend in the previous block
+		// to now be one is due to some transaction in the current block
+		// (probably the same one) also spending those outputs, and, in that
+		// case, anything that happens to be in the pool which depends on the
+		// transaction is still valid.
+		if !headerApprovesParent(&block.MsgBlock().Header) {
+			for _, tx := range parentBlock.Transactions()[1:] {
+				_, err := txMemPool.MaybeAcceptTransaction(tx, false, true)
+				if !isDoubleSpendOrDuplicateError(err) {
```
[the remark this answers is not in the document]
Comment (davecgh) [reply blockmanager.go]: Nice catch. I was looking through some of my local branch history and noticed I already had:

```
if err != nil && !isDoubleSpendOrDuplicateError(err) {
```

Somehow that didn't make it in though. I'll go through and verify everything else to make sure I didn't miss adding anything else to the commit.

Updated.

File: blockmanager.go [hunk 6]
```diff
@@ -1869,48 +1923,60 @@ func (b *blockManager) handleNotifyMsg(notification *blockchain.Notification) {
...
+		// The dependencies are not removed for double spends because the only
+		// way a transaction which was not a double spend in the block being
+		// disconnected to now be one is due to some transaction in the previous
+		// block (probably the same one), which was disapproved, also spending
+		// those outputs, and, in that case, anything that happens to be in the
+		// pool which depends on the transaction is still valid.
+		handleDisconnectedBlockTxns := func(txns []*dcrutil.Tx) {
+			for _, tx := range txns {
+				_, err := txMemPool.MaybeAcceptTransaction(tx, false, true)
+				if !isDoubleSpendOrDuplicateError(err) {
```
[the remark this answers is not in the document]
Comment (davecgh) [reply blockmanager.go]: Updated.

**Comment by davecgh** [comment]
The issue regarding reorgs of disapproved blocks as reported by @matheusd has been corrected.  In addition, tests for the scenario that triggered it have been added via PR #1485 so the scenario is proven to work the same both before and after this PR.

**Comment by davecgh** [comment]
All review items until this point have been addressed.

**Comment by davecgh** [comment]
Rebased to deal with conflicts with latest master.

**Comment by davecgh** [comment]
Some timing information for the large full block reorg tests with and without these changes:

```
without changes: 3m21.801s
with changes:    2m18.629s
```

**Comment by davecgh** [comment]
Rebased to handle merge conflicts with latest master and squashed all approved review updates.

**Comment by davecgh** [comment]
This is ready for final review and approvals.

**Comment by chappjc** [comment]
This branch has been in use on my dev machine and on alpha.dcrdata.org for weeks without issue.

File: blockchain/indexers/txindex.go (hunk 1 above)
Comment (davecgh) [reply blockchain/indexers/txindex.go]: I decided to open another PR (#1520) that contains the migration bits.
