### PR TITLE
rpcserver: Warn on alt DNS names when certs exist.

### LINKED ISSUE #1912: altdnsnames argument is not working
I want to call remote RPC connection and I removed old certificate then I run with altdnsnames argument. The new certificate has been created but I still cannot call RPC connection it gives an error like that

`
Error: Peer certificate cannot be authenticated with given CA certificates
`

`/opt/decred/dcrd --altdnsnames="xxx.xxx.xxx.xxx,xxx.xxx.xxx.xxx"
`

My Decred Release
https://github.com/decred/decred-release/releases/download/v1.4.0/dcrinstall-linux-amd64-v1.4.0

### PR DESCRIPTION
**Pull request by davecgh**
This adds a warning when alternative DNS names are specified and the TLS certificate key or cert already exist to make it clear the additional names will NOT be included unless the certificate and key are deleted first.

Closes #1912.

### CODE REVIEW

File: server.go [hunk 1]
```diff
@@ -2475,9 +2475,17 @@ func setupRPCListeners() ([]net.Listener, error) {
...
+		keyFileExists := fileExists(cfg.RPCKey)
+		certFileExists := fileExists(cfg.RPCCert)
+		if len(cfg.AltDNSNames) != 0 && (keyFileExists || certFileExists) {
+			rpcsLog.Warn("Additional DNS names specified when TLS " +
+				"certificates already exist will NOT be included:")
+			rpcsLog.Warnf("- In order to create TLS certs that include the "+
+				"additional DNS names, delete %q and %q and restart the server",
+				cfg.RPCKey, cfg.RPCCert)
+		}
+		if !keyFileExists && !certFileExists {
```
Comment (chappjc) [inline server.go]: This isn't a change of logic, but I've previously wondered why this isn't an `||`.  If either key or cert do not exist, how can the RPC server be expected to start?

Comment (davecgh) [reply server.go]: If one is missing the call just below to `tls.LoadX509KeyPair` will fail with an obvious missing file message.  This check is an `&&` so that it only attempt to generate new certificates when neither file exists since if one or the other exists, the user probably has done something wonky and we don't want to just wipe out their existing file blindly.
