### PR TITLE
rpcwebsocket: Fix formatted error logging.

### LINKED ISSUE #695: new tickets notification has incorrect type
It is returning []string instead of map[string]string.  This causes dcrrpcclient to throw an error: Received invalid new tickets notification: json: cannot unmarshal array into Go value of type map[string]string

### PR DESCRIPTION
**Pull request by jolan**

### CODE REVIEW

File: rpcwebsocket.go [hunk 1]
```diff
@@ -971,18 +971,18 @@ func (*wsNotificationManager) notifyNewTickets(clients map[chan struct{}]*wsClie
 	tnd *blockchain.TicketNotificationsData) {
 
 	// Create a ticket map to export as JSON.
-	var tickets []string
-	for _, h := range tnd.TicketsNew {
-		tickets = append(tickets, h.String())
+	ticketMap := make(map[string]string)
+	for i, ticket := range tnd.TicketsNew {
+		ticketMap[strconv.Itoa(i)] = ticket.String()
```
Comment (chappjc) [inline rpcwebsocket.go]: This makes sense for the missed and spend notifications because the map is a hash key to a string value ("missed" or "spend"), but what's the point of a map here?  Or in the winning ticket notification for that matter?

Comment (jolan) [inline rpcwebsocket.go]: That seemed silly to me too but I figured it wasn't worth changing this and winning tickets.  Winning tickets especially since It's already being used as-is in stakepoold.

Comment (chappjc) [inline rpcwebsocket.go]: OK, I was just wondering if the mistake was the winning ticket notification rather than this one.
