### PR TITLE
rpcserver/chain: Bounds check getstakeversions.

### LINKED ISSUE #635: RPC: panic when calling getstakeversions with a negative number.
The following panic was reported by chapjc on slack:

``` 
panic: runtime error: makeslice: cap out of range goroutine

1674 [running]:
github.com/decred/dcrd/blockchain.(*BlockChain).GetStakeVersions(0xc420130000, 0xc42154e0c0, 0xc4fffffe8e, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/j/go/src/github.com/decred/dcrd/blockchain/chain.go:316 +0x127
main.handleGetStakeVersions(0xc42000b100, 0xa5b780, 0xc42154e040, 0x0, 0xc4204119d0, 0xc42168d201, 0xc42009ef70, 0xc4200f0090)
        /home/j/go/src/github.com/decred/dcrd/rpcserver.go:3949 +0xb6
main.(*rpcServer).standardCmdResult(0xc42000b100, 0xc421a2fb00, 0x0, 0x10, 0x105d360, 0x0, 0x0)
        /home/j/go/src/github.com/decred/dcrd/rpcserver.go:6213 +0x97
main.(*wsClient).handleMessage(0xc421a58f30, 0xc421d53800, 0x88, 0x600)
        /home/j/go/src/github.com/decred/dcrd/rpcwebsocket.go:1410 +0x89b
main.(*wsClient).inHandler(0xc421a58f30)
        /home/j/go/src/github.com/decred/dcrd/rpcwebsocket.go:1455 +0xac
created by main.(*wsClient).Start
        /home/j/go/src/github.com/decred/dcrd/rpcwebsocket.go:1740 +0x107
```

I have traced this down to being caused by neither the RPC handler, nor the `GetStakeVersions` checking the input arguments for correctness.

### PR DESCRIPTION
**Pull request by davecgh**
This adds bounds check for the RPC parameters for the `getstakeversions` command to both the handler and the chain function itself which provides the data.

Also, while here simplify the for loop in `GetStakeVersions` to check `prevNode` in the for loops condition instead of in a separate if block, return more appropriate error types for RPC parameter type errors, and
make use a naked type cast of the command to be consistent with all of the other handlers.

Fixes #635

### CODE REVIEW

File: blockchain/chain.go [hunk 1]
```diff
@@ -305,17 +305,31 @@ type StakeVersions struct {
...
+	// Nothing to do if no count requested.
+	if count == 0 {
+		return nil, nil
+	}
+
 	b.chainLock.Lock()
 	defer b.chainLock.Unlock()
 
+	// Enforce sane count bounds.
+	if count < 0 {
```
Comment (jrick) [inline blockchain/chain.go]: these can be checked without the chainlock held.

Comment (jrick) [inline blockchain/chain.go]: well, unsure about the best node, but this negative check certainly could.

Comment (davecgh) [inline blockchain/chain.go]: Well this one can, but the next one (`bestNode`) can't. Good observation. Updated.
