### PR TITLE
rpcserver: Handle getwork nil err during reorg.

### LINKED ISSUE #2699: getwork panic when CurrentTemplate return nil template and nil error
I got a panic on a `getwork` request (recovered by http handler) on testnet3:

```
2021-08-04 14:43:43.184 [ERR] RPCS: http: panic serving [::1]:45694: runtime error: invalid memory address or nil pointer dereference                                                                                   
goroutine 2204410 [running]:                                                                                
net/http.(*conn).serve.func1(0xc000110460)                                                                  
        /usr/lib/go/src/net/http/server.go:1824 +0x153                                                      
panic(0xa40c80, 0x103bbe0)                                                                                                                                                                                              
        /usr/lib/go/src/runtime/panic.go:971 +0x499                                                         
github.com/decred/dcrd/internal/rpcserver.handleGetWorkRequest(0xc000270580, 0xc019d31e01, 0x7, 0x1, 0x2100000000721c2d)                                                                                                
        /decred/dcrd/internal/rpcserver/rpcserver.go:3753 +0x6f0                            
github.com/decred/dcrd/internal/rpcserver.handleGetWork(0xd2b558, 0xc016f24280, 0xc000270580, 0xa034c0, 0xc021be3098, 0x0, 0x0, 0x0, 0x0)                                                                               
        /decred/dcrd/internal/rpcserver/rpcserver.go:3951 +0x13f                            
github.com/decred/dcrd/internal/rpcserver.(*Server).standardCmdResult(0xc000270580, 0xd2b558, 0xc016f24280, 0xc021bca3c0, 0xc000118658, 0xa, 0xa00880, 0xc021bca370)
```

The above are release-v1.6 line numbers, but the code in question is the same on master:

https://github.com/decred/dcrd/blob/75b0f68a3583b8fb49e58151f283fdd63572e451/internal/rpcserver/rpcserver.go#L3689-L3691

It appears that `err` was `nil`, but this branch must have been taken because `template == nil`.  I don't know the significance of this circumstance.

### PR DESCRIPTION
**Pull request by davecgh**
This modifies the `getwork` RPC to properly handle the case when both the template and the error are nil which happens if the caller makes a request during a chain reorganization.

It also adds a test for the condition to prevent regressions.

Fixes #2699.

### CODE REVIEW

File: internal/rpcserver/rpcserverhandlers_test.go [hunk 1]
```diff
@@ -6159,6 +6159,18 @@ func TestHandleGetWork(t *testing.T) {
 		}(),
 		wantErr: true,
 		errCode: dcrjson.ErrRPCInternal.Code,
+	}, {
+		name:    "handleGetWork: no work during chain reorg",
+		handler: handleGetWork,
+		cmd:     &types.GetWorkCmd{},
```
Comment (rstaudt2) [inline internal/rpcserver/rpcserverhandlers_test.go:6165]: I believe you need to add `mockMiningState: mine(),` here in order to hit the code in question.

File: internal/rpcserver/rpcserver.go [hunk 2]
```diff
@@ -3686,10 +3686,14 @@ func handleGetWorkRequest(s *Server) (interface{}, error) {
 	if template == nil {
 		var err error
 		template, err = bt.CurrentTemplate()
-		if err != nil || template == nil {
+		if err != nil {
 			context := "Unable to retrieve work due to invalid template"
 			return nil, rpcInternalError(err.Error(), context)
 		}
+		if template == nil {
```
Comment (rstaudt2) [inline internal/rpcserver/rpcserver.go:3693]: This is already guarded by `template == nil`, so no need to check again.

File: internal/rpcserver/rpcserverhandlers_test.go [hunk 3]
```diff
@@ -6159,6 +6159,18 @@ func TestHandleGetWork(t *testing.T) {
...
+		mockBlockTemplater: func() *testBlockTemplater {
+			templater := defaultMockBlockTemplater()
+			templater.currTemplate = nil
+			templater.currTemplateErr = nil
+			return templater
+		}(),
+		wantErr: true,
+		errCode: dcrjson.ErrRPCInternal.Code,
```
Comment (rstaudt2) [inline internal/rpcserver/rpcserverhandlers_test.go:6173]: It should be `dcrjson.ErrRPCMisc`, but it looks like a different error path is being hit.

**Review by rstaudt2 — COMMENTED** [review]
I confirmed this fixes the panic in the referenced issue, just had a few comments inline.

File: internal/rpcserver/rpcserver.go (hunk 2 above)
Comment (davecgh) [reply internal/rpcserver/rpcserver.go:3693]: See line 3688, it updates `template` which typically will make it non-nil, but the specific case in question here is when it doesn't.

Comment (rstaudt2) [reply internal/rpcserver/rpcserver.go:3693]: Ah, right.  Disregard that comment.

File: internal/rpcserver/rpcserverhandlers_test.go (hunk 3 above)
Comment (davecgh) [reply internal/rpcserver/rpcserverhandlers_test.go]: You're right.  I've updated the test now.  I also added a print in the path in question during testing to confirm it was being hit that way.

File: internal/rpcserver/rpcserverhandlers_test.go (hunk 1 above)
Comment (davecgh) [reply internal/rpcserver/rpcserverhandlers_test.go:6165]: Updated.  I wasn't able to use the using `mine` because that one doesn't set the previous state to the necessary value to skip the initial template retrieval via the template subscription, but you're correct that a mining state was needed.

I had originally put `mine` there when writing the test, but it was going down the aforementioned path incorrectly and I thought removing it would cause the default state to be set properly, but after digging in based on your comment here, I see that wasn't the case either.

Anyway, it's correct now.

**Review by rstaudt2 — APPROVED** [review]

File: internal/rpcserver/rpcserverhandlers_test.go (hunk 3 above)
Comment (davecgh) [reply internal/rpcserver/rpcserverhandlers_test.go]: I also reverted the fix and observed the test panic, so it is indeed hitting the right thing.

**Review by jrick — APPROVED** [review]

**Review by JoeGruffins — APPROVED** [review]
