### PR TITLE
dcrctl: Fix --skipverify failing if rpc.cert not found.

### LINKED ISSUE #1156: dcrctl --skipverify fails if certificate is not found
It should not.

### PR DESCRIPTION
**Pull request by vctt94**
closes #1156

### CODE REVIEW

File: cmd/dcrctl/httpclient.go [hunk 1]
```diff
@@ -72,7 +72,7 @@ func newHTTPClient(cfg *config) (*http.Client, error) {
 func sendPostRequest(marshalledJSON []byte, cfg *config) ([]byte, error) {
 	// Generate a request to the configured RPC server.
 	protocol := "http"
-	if !cfg.NoTLS {
+	if !cfg.NoTLS && !cfg.TLSSkipVerify {
```
Comment (dajohi) [inline cmd/dcrctl/httpclient.go]: This doesn't seem correct.   Skipping verify shouldn't not disable https;  it should disable cert verification.

Comment (dajohi) [reply cmd/dcrctl/httpclient.go]: https://golang.org/pkg/crypto/tls/#Config

InsecureSkipVerify

**Comment by vctt94** [comment]
Thanks for reviewing my PR. I removed unnecessary TLS changes and I am verifying the connection now.

File: cmd/dcrctl/httpclient.go [hunk 2]
```diff
@@ -38,20 +38,22 @@ func newHTTPClient(cfg *config) (*http.Client, error) {
...
-			return nil, err
-		}
-
-		pool := x509.NewCertPool()
-		if ok := pool.AppendCertsFromPEM(pem); !ok {
-			return nil, fmt.Errorf("invalid certificate file: %v",
-				cfg.RPCCert)
-		}
 		tlsConfig = &tls.Config{
-			RootCAs:            pool,
```
Comment (dajohi) [inline cmd/dcrctl/httpclient.go]: tlsConfig.InsecureSkipVerify = cfg.TLSSkipVerify

**Comment by davecgh** [comment]
NACK.  A @jrick notes, this change is not correct.  The `--skipverify` does *not* mean `--notls`.  The certificates are required for `--skipverify`, because the TLS connection still has to be made, rather it just does not verify the certificate chain or hostname and thus is susceptible to MITM (man-in-the-middle) attacks.

If you're trying to not use the `rpc.cert` then you want to use the `--notls` option.

File: cmd/dcrctl/httpclient.go [hunk 3]
```diff
@@ -38,20 +38,22 @@ func newHTTPClient(cfg *config) (*http.Client, error) {
 	// Configure TLS if needed.
 	var tlsConfig *tls.Config
 	if !cfg.NoTLS && cfg.RPCCert != "" {
```
Comment (davecgh) [inline cmd/dcrctl/httpclient.go]: The check for `cfg.RPCCert != ""` needs to be moved down with the `!cfg.TLSSkipVerify` check, otherwise it will not create the TLS config at all when `RPCCert` path is not set.
