### PR TITLE
cpuminer: fix race.

### LINKED ISSUE #1897: cpuminer: data race
```
2019-09-11 18:37:57.895 [TRC] MINR: Adding tx 9f2104145a88c0e43cd7918ecdac92fea1418b370d3f7550b1e30920fcd8b18b (priority 0.00, feePerKB 10446.78)                                                                               [172/1781]
2019-09-11 18:37:58.072 [DBG] MINR: Created new block template (17 transactions, 4 stake transactions, 320054 in fees, 223 signature operations, 97876 bytes, target difficulty 0000001c3ea40000000000000000000000000000000000000000000000
000000, stake difficulty 47.33664425)
2019-09-11 18:38:01.084 [DBG] MINR: Hash speed:     40 kilohashes/s
==================
WARNING: DATA RACE
Write at 0x00c001f2df98 by goroutine 75:
  main.(*CPUMiner).SetNumWorkers()
      /home/dcrd/.go/src/github.com/decred/dcrd/cpuminer.go:571 +0x122
  main.handleSetGenerate()
      /home/dcrd/.go/src/github.com/decred/dcrd/rpcserver.go:4172 +0x1a2
  main.(*rpcServer).standardCmdResult()
      /home/dcrd/.go/src/github.com/decred/dcrd/rpcserver.go:5056 +0x146
  main.(*rpcServer).processRequest()
      /home/dcrd/.go/src/github.com/decred/dcrd/rpcserver.go:5145 +0x715
  main.(*rpcServer).jsonRPCRead()
      /home/dcrd/.go/src/github.com/decred/dcrd/rpcserver.go:5241 +0x2586
  main.(*rpcServer).Start.func1()
      /home/dcrd/.go/src/github.com/decred/dcrd/rpcserver.go:5422 +0x3a6
  net/http.HandlerFunc.ServeHTTP()
      /home/dcrd/go/src/net/http/server.go:1995 +0x51
  net/http.(*ServeMux).ServeHTTP()
      /home/dcrd/go/src/net/http/server.go:2375 +0x28a
  net/http.serverHandler.ServeHTTP()
      /home/dcrd/go/src/net/http/server.go:2774 +0xce
  net/http.(*conn).serve()
      /home/dcrd/go/src/net/http/server.go:1878 +0x811

Previous read at 0x00c001f2df98 by goroutine 50:
  main.(*CPUMiner).miningWorkerController()
      /home/dcrd/.go/src/github.com/decred/dcrd/cpuminer.go:460 +0x2c3

Goroutine 75 (running) created at:
  net/http.(*Server).Serve()
      /home/dcrd/go/src/net/http/server.go:2884 +0x4c4
  main.(*rpcServer).Start.func3()
      /home/dcrd/.go/src/github.com/decred/dcrd/rpcserver.go:5452 +0x12c

Goroutine 50 (running) created at:
  main.(*CPUMiner).Start()
      /home/dcrd/.go/src/github.com/decred/dcrd/cpuminer.go:497 +0x14a
  main.(*server).Start()
      /home/dcrd/.go/src/github.com/decred/dcrd/server.go:2300 +0x23c
  main.dcrdMain()
      /home/dcrd/.go/src/github.com/decred/dcrd/dcrd.go:196 +0x139c
  github.com/btcsuite/goleveldb/leveldb/storage.fsParseName()
      /home/dcrd/go/src/fmt/scan.go:114 +0x193
  github.com/btcsuite/goleveldb/leveldb/storage.(*fileStorage).List()
      /home/dcrd/.go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/storage/file_storage.go:458 +0x2b3
  fmt.Fscanf()
      /home/dcrd/go/src/fmt/scan.go:143 +0xcf
  github.com/btcsuite/goleveldb/leveldb/storage.fsParseName()
      /home/dcrd/go/src/fmt/scan.go:114 +0x286
  fmt.(*ss).doScanf()
      /home/dcrd/go/src/fmt/scan.go:1193 +0x377
....
```

### PR DESCRIPTION
**Pull request by dnldd**
Closes #1897

### CODE REVIEW

File: cpuminer.go [hunk 1]
```diff
@@ -684,13 +686,16 @@ func (m *CPUMiner) GenerateNBlocks(n uint32) ([]*chainhash.Hash, error) {
...
 		g:                 cfg.BlockTemplateGenerator,
 		cfg:               cfg,
-		numWorkers:        defaultNumWorkers,
 		updateNumWorkers:  make(chan struct{}),
 		queryHashesPerSec: make(chan float64),
 		updateHashes:      make(chan uint64),
 		minedOnParents:    make(map[chainhash.Hash]uint8),
 	}
+
+	atomic.StoreUint32(&cpu.numWorkers, defaultNumWorkers)
```
Comment (davecgh) [inline cpuminer.go]: No need to do this.  It can be initialized normally.
